Implement case insensitive answers
co-code/pidor-bot pull request #13
Opened 2017-08-09 15:39 UTC by nikitabelonogov

2017-08-09 15:40 UTC, wlad031 requested changes

2017-08-09 15:40 UTC, wlad031 commented on test/test_dialog_engine.py
> +            'ПрBвЕт': [
mistyping?

2017-08-09 15:51 UTC, nikitabelonogov commented on test/test_dialog_engine.py
> +            'ПрBвЕт': [
no

2017-08-09 15:57 UTC, nikitabelonogov commented on test/test_dialog_engine.py
> +            'ПрBвЕт': [
yes

2017-08-09 16:02 UTC, wlad031 submitted a review, later dismissed

2017-08-09 17:02 UTC, wlad031 approved these changes

2017-08-09 17:02 UTC, merged

2017-08-09 17:03 UTC, wlad031 commented
Could you release this version?

2017-08-10 06:39 UTC, nikitabelonogov commented
Ok, I've also ban opportunity to perform merge and rebase merging in PRs just FYI