Move answers to separated JSON file
co-code/pidor-bot pull request #9
Opened 2017-08-03 19:54 UTC by wlad031

2017-08-04 05:42 UTC, wlad031 commented
Not for merge yet

2017-08-04 08:22 UTC, nikitabelonogov requested changes

2017-08-04 08:22 UTC, nikitabelonogov commented on run.py
> +            'statusCode': 500,
если мы кидаем 500 ошибку обратно на вебхук, запрос будет перезапущен позже
не приведёт ли это к зацикливанию?

2017-08-04 08:24 UTC, wlad031 commented on run.py
> +            'statusCode': 500,
I don't understand you, could you please use english?

2017-08-04 08:29 UTC, wlad031 commented on run.py
> +            'statusCode': 500,
> если мы кидаем 500 ошибку обратно на вебхук, запрос будет перезапущен позже
я не знал(

2017-08-04 08:36 UTC, nikitabelonogov commented on run.py
> +            'statusCode': 500,
ye, sure
If we throw a 500 error back on the webhook, the request will be restarted later
Will this lead to a loop?

2017-08-04 08:37 UTC, wlad031 commented on run.py
> +            'statusCode': 500,
> If we throw a 500 error back on the webhook, the request will be restarted later

I didn't know that(

2017-08-08 10:40 UTC, wlad031 commented
@nikitabelonogov pls, review

2017-08-08 12:52 UTC, wlad031 commented on dialog/answers.py
> +        '))))))))))))',
))))

2017-08-08 12:52 UTC, wlad031 commented on dialog/answers.py
> -        'го бухать',
((((

2017-08-08 12:54 UTC, nikitabelonogov commented on dialog/answers.py
> -        'го бухать',
a joke about racoon is too local

2017-08-08 12:55 UTC, nikitabelonogov approved these changes

2017-08-08 12:55 UTC, merged

2017-08-08 12:56 UTC, wlad031 commented on dialog/answers.py
> -        'го бухать',
will we share our bot with telegram community?

2017-08-08 13:17 UTC, nikitabelonogov commented on dialog/answers.py
> -        'го бухать',
definitely yes